package com.group3.ticketing.project.Model;

import jakarta.persistence.*;

/**
 * Passenger entity class that maps to the "Passenger" table in the database.
 * Represents a passenger with an auto-generated ID, name, email, and phone number.
 */
@Entity
@Table(name = "Passenger")   // Specifies the table name in the database
public class Passenger {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)   // Auto-generates IDs (incrementing primary key)
    @Column(name = "pId")   // Maps to the "pId" column in the Passenger table
    private int pId;

    @Column(name = "pName")  // Maps to the "pName" column
    private String pName;

    @Column(name = "email")  // Maps to the "email" column
    private String email;

    @Column(name = "phone")  // Maps to the "phone" column
    private String phone;
    
    @Column (name = "passcode")  //Maps to the "passcode" column
    private String passcode;

    /**
     * Default constructor required by JPA.
     */
    public Passenger() {}

    /**
     * Constructor used for creating a Passenger object without specifying the ID
     * (since the ID is auto-generated by the database).
     *
     * @param pName passenger's name
     * @param email passenger's email
     * @param phone passenger's phone number
     * @param passcode passenger's passcode
     */
    public Passenger(String pName, String email, String passcode, String phone) {
        this.pName = pName;
        this.email = email;
        this.phone = phone;
        this.passcode = passcode;
    }

    /**
     * Gets the passenger's unique ID.
     *
     * @return the passenger ID
     */
    public int getpId() {
        return pId;
    }

    /**
     * Sets the passenger's ID.
     * Note: normally not set manually, since it's auto-generated by the database.
     *
     * @param pId the passenger ID
     */
    public void setpId(int pId) {
        this.pId = pId;
    }

    /**
     * Gets the passenger's name.
     *
     * @return the passenger's name
     */
    public String getpName() {
        return pName;
    }

    /**
     * Sets the passenger's name.
     *
     * @param pName the passenger's name
     */
    public void setpName(String pName) {
        this.pName = pName;
    }

    /**
     * Gets the passenger's email address.
     *
     * @return the passenger's email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the passenger's email address.
     *
     * @param email the passenger's email
     */
    public void setEmail(String email) {
        this.email = email;
    }
    
    
    /**
     * Gets the passenger's account passcode.
     *
     * @return the passenger's passcode
     */
    public String getPasscode() {
        return passcode;
    }

    /**
     * Sets the passenger's passcode.
     *
     * @param passcode the passenger's passcode
     */
    public void setPasscode(String passcode) {
        this.passcode = passcode;
    }
 

    /**
     * Gets the passenger's phone number.
     *
     * @return the passenger's phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the passenger's phone number.
     *
     * @param phone the passenger's phone
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}
